grails:
    profile: plugin
    doc:
        title: RabbitMQ Native Plugin
        authors: Bud Byrd
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
