language: java

jdk:
- oraclejdk8

services:
- rabbitmq

before_script:
- sudo rabbitmqctl add_vhost test1.rabbitmq.budjb.com
- sudo rabbitmqctl add_vhost test2.rabbitmq.budjb.com
- sudo rabbitmqctl set_permissions -p test1.rabbitmq.budjb.com guest ".*" ".*" ".*"
- sudo rabbitmqctl set_permissions -p test2.rabbitmq.budjb.com guest ".*" ".*" ".*"

script:
- ./gradlew --refresh-dependencies test integrationTest
