---
grails:
    profile: plugin

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

---
rabbitmq:
    connections:
        connection1:
            host: 'localhost'
            username: 'guest'
            password: 'guest'
            virtualHost: 'test1.rabbitmq.budjb.com'
            isDefault: true
            name: 'connection1'

        connection2:
            host: 'localhost'
            username: 'guest'
            password: 'guest'
            virtualHost: 'test2.rabbitmq.budjb.com'
            name: 'connection2'

    exchanges:
        topic-exchange:
            type: topic
            autoDelete: true

    queues:
        reporting:
            autoDelete: true
            connection: connection1
        sleeping:
            autoDelete: true
            connection: connection1
        string-test:
            autoDelete: true
            connection: connection1
        topic-queue-all:
            autoDelete: true
            binding: '#'
            connection: connection1
            exchange: topic-exchange
        topic-queue-subset:
            autoDelete: true
            binding: 'com.budjb.#'
            connection: connection1
            exchange: topic-exchange
        topic-queue-specific:
            autoDelete: true
            binding: 'com.budjb.rabbitmq'
            connection: connection1
            exchange: topic-exchange
        connection2-queue:
            autoDelete: true
            connection: connection2
